name: Session Variables
pname: session_variables
description: Flow session variables management
version: 0.1.1
icon: code
private: false
base: true
category: app_flow_management
python:
  - '3.9'
  - '3.10'
  - '3.11'
  - '3.12'
